#
# VPC demo-vpc-3 and its attachment to server-3
#
apiVersion: vpc.githedgehog.com/v1alpha2
kind: VPC
metadata:
  name: demo-vpc-3
  namespace: default
spec:
  subnets:
    subnet-1:
      subnet: 10.30.131.0/24
      gateway: 10.30.131.1
      vlan: 1131
      dhcp:
        enable: true
        range:
          start: 10.30.131.10
          end: 10.30.131.99
    subnet-2:
      subnet: 10.30.132.0/24
      vlan: 1132
      isolated: true
      restricted: true
      dhcp:
        enable: true
  permit:
    - [subnet-1, subnet-2]
---
# apiVersion: vpc.githedgehog.com/v1alpha2
# kind: VPCAttachment
# metadata:
#   name: demo-vpc-3--server-3--unbundled--as7326-01
#   namespace: default
# spec:
#   connection: server-3--unbundled--as7326-01
#   subnet: demo-vpc-3/subnet-1

#
# VPC Peering: vpc-1 <> vpc-2
#
---
apiVersion: vpc.githedgehog.com/v1alpha2
kind: VPCPeering
metadata:
  name: demo-vpc-1--demo-vpc-2
  namespace: default
spec:
  permit:
    - demo-vpc-1:
        subnets: [default]
      demo-vpc-2:
        subnets: [default]

#
# External Peering: vpc-1 <> external
#
---
apiVersion: vpc.githedgehog.com/v1alpha2
kind: ExternalPeering
metadata:
  name: demo-vpc-1--default--5835
  namespace: default
spec:
  permit:
    external:
      name: default--5835
      prefixes:
        - prefix: 0.0.0.0/0
    vpc:
      name: demo-vpc-1
      subnets:
        - default
