apiVersion: vpc.githedgehog.com/v1beta1
kind: VPC
metadata:
  name: demo-vpc-1
  namespace: default
spec:
  subnets:
    default:
      subnet: 10.10.101.0/24
      vlan: 1101
      dhcp:
        enable: true
        range:
          start: 10.10.101.10
          end: 10.10.101.99
---
apiVersion: vpc.githedgehog.com/v1beta1
kind: VPC
metadata:
  name: demo-vpc-2
  namespace: default
spec:
  subnets:
    default:
      subnet: 10.10.102.0/24
      vlan: 1102
      dhcp:
        enable: true
        range:
          start: 10.10.102.10
          end: 10.10.102.99
---
apiVersion: vpc.githedgehog.com/v1beta1
kind: VPCAttachment
metadata:
  name: demo-vpc-1--server-1--mclag--s5248-01--s5248-02
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  connection: server-1--mclag--s5248-01--s5248-02
  subnet: demo-vpc-1/default
---
apiVersion: vpc.githedgehog.com/v1beta1
kind: VPCAttachment
metadata:
  name: demo-vpc-2--server-4--unbundled--s5248-02
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  connection: server-4--unbundled--s5248-02
  subnet: demo-vpc-2/default
