apiVersion: vpc.githedgehog.com/v1alpha2
kind: VPC
metadata:
  name: vpc-test
  namespace: default
spec:
  subnets:
    default:
      subnet: 10.10.200.0/24
      vlan: 1200
      dhcp:
        enable: true
        range:
          end: 10.10.200.99
